<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru">

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />

	<title><?=$this->title ? $this->escape($this->title) : ''?></title>

	<?=$this->headLink()
		//->appendStylesheet($this->baseUrl('css/style.css'))
		//->appendStylesheet($this->baseUrl('css/item.css'))
	?>

	<?=$this->headScript()
		//->appendFile($this->baseUrl('js/mootools.js'))
		//->appendFile($this->baseUrl('js/mootools-more.js'))
	?>
</head>
<body>
	<div style="border: solid 1px #ccc;overflow: hidden;">
		<p>Content area</p>
		<?=$this->layout()->content?>
	</div>
</body>
</html>